# Generated by Django 5.2.1 on 2025-05-23 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_contextmenu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Банковская карта'), (1, 'Наличные'), (2, 'QR-код'), (3, 'СБП перевод')], default=0, verbose_name='Метод оплаты'),
        ),
    ]
