# Generated by Django 5.2.1 on 2025-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_category_user_alter_operation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextmenu',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='sort_order'),
        ),
    ]
